name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: /tmp/go-cache
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod tidy

    - name: Run GolangCI-Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.44.0  # Adjust to the version you want
        args: --disable-all --enable=govet --enable=gocyclo --enable=gofmt  # Enable desired linters

    - name: Run tests
      run: go test ./... -v  # Run all tests

    - name: Build application
      run: go build -o main .  # Build the Go application
